config:
  connection:
    platform: vaas
    credentials:
      apiKey: '2ffa71a3-bff2-4de2-908e-7ba4a82c69f6' # APIKEY as Environment variable
certificateTasks:
  - name: myCertificate # Task Identifier
    renewBefore: 31d
    setEnvVars: ["thumbprint", "serial"] #will set environment variables VCERT_TASKNAME_THUMBPRINT and VCERT_TASKNAME_SERIAL
    request:
      csr: local
      subject:
        # Templating needs to go between single quotes to avoid issues when refreshing tokens and saving back
        commonName: 'bootcamp.cyberark.com'
        country: US
        locality: Salt Lake City
        state: Utah
        organization: Venafi Inc
        orgUnits:
          - engineering
          - marketing
      zone: "Test app\\Default"
    installations:
      - format: PEM
        file: "/Users/saket.agarwalla/Downloads/vcert_v5.13.2_darwin/certificate/cert.pem"
        chainFile: "/Users/saket.agarwalla/Downloads/vcert_v5.13.2_darwin/certificate/chain.cer"
        keyFile: "/Users/saket.agarwalla/Downloads/vcert_v5.13.2_darwin/certificate/key.pem"
        afterInstallAction: "echo Success!!!"


*NFcIxMf!@EGIECg


run-name: Test CyberArk Integration
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch test
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tabs
  workflow_dispatch:

 
jobs:
  cyberark-integration:
    permissions:
      id-token: 'write'
      contents: 'read'
    runs-on: ubuntu-latest
 
    steps:


      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: cyberark/conjur-action@v2.0.6
        with:
          url: https://demo.secretsmgr.cyberark.cloud/api
          account: conjur
          authn_id: github_sa
          secrets: data/vault/cyberarkshop-automation-demo/cyberarkshop-trust-anchor/username|password
      
      - name: echo secrets
        run: |
          echo ${password} | sed 's/./& /g'
          env | sed 's/./& /g' | grep "P A S S W O R D"
          # | sets the result into an env variable
